#pragma once
#include <iostream>
#include <string>
#include <sstream>
#include <ctype.h>
#include <vector>
#include <iterator>
#include <fstream>
#include <sstream>
#include "Validation.h"
#include "Person.h"
#include "Client.h"
#include "Employee.h"
#include "Admin.h"
#include "Parser.h"
#include "FileHelper.h"
#include "DataSourceInterface.h"
#include "FileManger.h"